### PR TITLE
Add support for RSA OAEP encoding

### PR DESCRIPTION
**Pull request by yapcwed**
@leocavalcante Thought it would make sense to support OAEP encoding as well.

### CODE REVIEW

**Comment by leocavalcante** [comment]
THank you!

**Comment by mnesarco** [comment]
Hi Friends,
Does OAEP encoding support only SHA1 digest? I am trying to use OAEP(SHA256, MGF1) with no luck.

**Comment by leocavalcante** [comment]
Hi @mnesarco 
This lib is a wrapper around PointyCastle which really implements the algorithms.
Unfortunately, SHA1 is hard-coded there on the OAEP implementation:
https://github.com/PointyCastle/pointycastle/blob/master/lib/asymmetric/oaep.dart#L32

**Comment by mnesarco** [comment]
Thank you @leocavalcante , I finally changed the backend code to use SHA-1 :(

**Pull request merged**
